# -*- coding: utf-8 -*-
"""bfsrep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F4C87XjfVntkUg2XuP9G3b-Cuyw6_4NS
"""

visited = [] # List for visited nodes.
queue = [] #Initialize a queue

# Define the graph (example)
graph = {
    '5' : ['3','7'],
    '3' : ['2', '4'],
    '7' : ['8'],
    '2' : [],
    '4' : ['8'],
    '8' : []
}

def bfs(visited, graph, node): #function for BFS
  visited.append(node)
  queue.append(node)
  while queue: # Creating loop to visit each node
    m = queue.pop(0)
    print (m, end = " ")
    for neighbour in graph[m]:
      if neighbour not in visited:
        visited.append(neighbour)
        queue.append(neighbour)

# Driver Code
print("Following is the Breadth-First Search")
bfs(visited, graph, '5') # function calling

import collections

def printParents(node, adj, parent):

    if (parent == 0):
        print(node, "->Root")
    else:
        print(node, "->", parent)


    for cur in adj[node]:
        if (cur != parent):
            printParents(cur, adj, node)


def printChildren(Root, adj):

    q = collections.deque()


    q.append(Root)


    vis = [False] * len(adj)
    vis[Root] = True


    while (len(q) > 0):
        node = q.popleft()
        print(f"{node} -> ", end="")
        children_found = False
        for cur in adj[node]:

            if not vis[cur]:
                print(f"{cur} ", end="")
                vis[cur] = True
                q.append(cur)
                children_found = True
        if not children_found:
            print("No children", end="")
        print()


def printLeafNodes(Root, adj):
    leaf_nodes_found = False

    for i in range(1, len(adj)):

        if (len(adj[i]) == 1 and i != Root):
            print(i, end=" ")
            leaf_nodes_found = True
    if not leaf_nodes_found:
        print("No leaf nodes found.")
    print()


def printDegrees(Root, adj):

    for i in range(1, len(adj)):
        print(f"{i}: ", end="")


        if (i == Root):
            print(len(adj[i]))
        else:

            print(len(adj[i]) - 1)


N = 7
Root = 1


adj = []
for i in range(0, N + 1):
    adj.append([])


adj[1].append(2)
adj[2].append(1)
adj[1].append(3)
adj[3].append(1)
adj[1].append(4)
adj[4].append(1)
adj[2].append(5)
adj[5].append(2)
adj[2].append(6)
adj[6].append(2)
adj[4].append(7)
adj[7].append(4)


print("The parents of each node are:")
printParents(Root, adj, 0)


print("\nThe children of each node are:")
printChildren(Root, adj)


print("\nThe leaf nodes of the tree are:")
printLeafNodes(Root, adj)


print("\nThe degrees of each node are:")
printDegrees(Root, adj)